# Generated by Django 4.2.11 on 2026-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('student', 'Student / Post Doctoral'), ('faculty', 'Faculty Member'), ('government', 'Government Officer'), ('industry', 'Industry Professional')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('research_area', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
