# Generated by Django 4.2.11 on 2026-02-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='dietary_requirements',
        ),
    ]
